# Configuration for Label Actions - https://github.com/dessant/label-actions
# The `feature` label is added to issues
feature:
  issues:
    # Post a comment, `{issue-author}` is an optional placeholder
    comment: >
      :wave: @{issue-author}, please use our idea board to request new features.
    # Close the issue
    close: true

# The `wip` label is added to pull requests
wip:
  prs:
    # Add labels
    label:
      - 'contributor'
      - 'needs feedback'


