# Configuration for Label Actions - https://github.com/dessant/label-actions



# The `feature` label is added to issues
feature:
  issues:
    # Post a comment, `{issue-author}` is an optional placeholder
    label:
      - 'feature'

# The `wip` label is added to pull requests
wip:
  prs:
    # Add labels
    label:
      - 'contributor'
      - 'needs feedback'
