name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: Hey! 👋🏻 Thank you so much for raising an issue! The maintainers will get back to you soon for discussion over the issue! <br/> In the meantime join our <a href="https://discord.io/commclassroom">discord server</a> and checkout our <a href="https://www.youtube.com/c/KunalKushwaha/">YouTube</a> channel
        pr-message: Woah! This is your first Pull Request, Congratulations and thank you for your contribution! 🚀 The team will review it on <u>availability</u> 💫. <br/> In the meantime join our <a href="https://discord.io/commclassroom">discord server</a> and celeberate your first PR with us! or check out our <a href="https://www.youtube.com/c/KunalKushwaha/">YouTube channel</a>
