- name: Close Stale Issues

permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write

jobs:
  stale-bot-logic:
    runs-on: ubuntu-latest
    steps:
    - name: stale action from marketplace
      uses: actions/stale@v6.0.1